language: java

# Skip "install" stage:
install: true

# Use container-based infrastructure:
sudo: false

addons:
  apt:
    packages:
      - openjdk-6-jdk

# Keep Maven local repository between builds:
cache:
  directories:
    - '$HOME/.m2/repository'

env:
  - JDK=5
  - JDK=6
  - JDK=7
  - JDK=8
  - JDK=8
    ECJ=true
  - JDK=8-ea
  - JDK=9
  - JDK=10-ea

matrix:
  allow_failures:
    - env: JDK=8-ea
    - env: JDK=10-ea

script: ./.travis.sh
